server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 换成nginx的1111端口，做集群
        server-addr: 192.168.174.148:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'